name: Release Addon

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Mangle
        run: |
          VERSION=$(
            echo '${{ github.ref }}' |\
            sed -E -e 's#^refs/tags/v(.*?)$#\1#'
          )
          echo "RELEASE_VERSION=$VERSION" >> $GITHUB_ENV

          SHORT_VERSION=$(
            echo $VERSION |\
            sed -E 's#-.*?$##'
          )
          awk '/^v'$SHORT_VERSION'$/,/^$/' VERSIONS.txt > RELEASE_BODY.txt

          echo $VERSION
          echo $RELEASE_VERSION
          echo $SHORT_VERSION
          cat RELEASE_BODY.txt

      - name: Zip
        run: |
          zip -r WoWthing_Collector-${{ env.RELEASE_VERSION }}.zip libs/ LICENSE VERSIONS.txt *.lua *.toc

      - uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          body_path: 'RELEASE_BODY.txt'
          fail_on_unmatched_files: true
          files: '*.zip'
          prerelease: ${{ contains(env.RELEASE_VERSION, '-') }}
